---
output: html_document
---

```{r data viz setup, include=FALSE}
library(tidyverse)
```

# Data Visualization

Data visualization is a core component of both exploring data and communicating
results to others. The goal of data visualization is to present data in a
graphical way that shows the reader patterns that would not otherwise be
visible. Despite its ubiquity and importance, effective data visualization is
challenging, and while many tools and approaches exist there is no "gold
standard" to follow in any meaningful sense. Rather, an effective visualization
has the following properties:

1. Depicts accurate data
2. Depicts data accurately
3. Shows enough, but not too much, of the data for the viewer to gain insight
4. Is self contained - no additional information (except a caption) is required
   to understand the contents of the figure

Beyond these, a *great* visualization has some additional properties:

5. Exposes patterns in the data not easily observable by other methods
6. Invites the viewer to ask more questions about the data

In this chapter, we explore some of the principles of visualizing data and
present many examples of plots and data visualization strategies commonly used
in biological data analysis and bioinformatics.