---
output: html_document
---

# Data Wrangling

## The Tidyverse

[The tidyverse](https://www.tidyverse.org/) is "an opinionated collection of R
packages designed for data science." The packages are all designed to work
together with a unified approach that helps code look consistent and neat. In
the opinion of this author, the tidyverse practically changes the R language
from a principally statistical programming language into an efficient and
expressive data science language. While it is still important to understand the
language fundamentals presented in our [chapter on the R programming
language](#prog-basics), the tidyverse uses a distinct set of coding conventions
that lets it achieve greater expressiveness, conciseness, and correctness
relative to the base R language.

As a data science language, R+tidyverse (referred to as simply *tidyverse* in
this book) is strongly focused on operations related to loading, manipulating,
visualizing, summarizing, and analyzing data sets from many domains. While this
is a major strength of tidyverse and its community, it means that many
educational materials are written for this general use case, and not for those
practicing biological data analysis. While the general data manipulation
operations are often the same between biological data analysis and these general
case examples, biological analysis practitioners must nonetheless translate
concepts from these general cases to the common data analysis tasks they must
perform. Some analytical patterns are more common in biological data analysis
than others, so these materials focus on that subset of operations in this book
to aid the learning in applying the concepts to their problems as directly as
possible.

::: {.box .readmore}
* [R for Data Science - Data Wrangling Introduction](https://r4ds.had.co.nz/wrangle-intro.html)
* [ModernDive - Data Wrangling](https://moderndive.com/3-wrangling.html)
:::

## Tidyverse Basics {#dw-basics}

Since tidyverse is a set of packages that work together, you will often want to
load multiple packages at the same time. The tidyverse authors recognize this,
and defined a set of reasonable packages to load at once when loading the
metapackage (i.e. a package that contains multiple packages):

```
library(tidyverse)
-- Attaching packages --------------------------------------------- tidyverse 1.3.1 --
v ggplot2 3.3.5     v purrr   0.3.4
v tibble  3.1.6     v dplyr   1.0.7
v tidyr   1.1.4     v stringr 1.4.0
v readr   2.1.1     v forcats 0.5.1
-- Conflicts ------------------------------------------------ tidyverse_conflicts() --
x dplyr::filter() masks stats::filter()
x dplyr::lag()    masks stats::lag()
```

The packages in the `Attaching packages` section are those loaded by default,
and each of these packages adds a unique set of functions to your R environment.
We will mention functions from many of these packages as we go through this
chapter, but for now here is a table of these packages and briefly what they do:

+-------------------------------------------+------------------------------------------------+
| Package                                   | Description                                    |
+===========================================+================================================+
| [ggplot2](https://ggplot2.tidyverse.org/) | Plotting using the grammar of graphics         |
+-------------------------------------------+------------------------------------------------+
| [tibble](https://tibble.tidyverse.org/)   | Simple and sane data frames                    |
+-------------------------------------------+------------------------------------------------+
| [tidyr](https://tidyr.tidyverse.org/)     | Operations for making data "tidy"              |
+-------------------------------------------+------------------------------------------------+
| [readr](https://readr.tidyverse.org/)     | Read rectangular text data into tidyverse      |
+-------------------------------------------+------------------------------------------------+
| [purrr](https://purrr.tidyverse.org/)     | Functional programming tools for tidyverse     |
+-------------------------------------------+------------------------------------------------+
| [dplyr](https://dplyr.tidyverse.org/)     | "A Grammar of Data Manipulation"               |
+-------------------------------------------+------------------------------------------------+
| [stringr](https://stringr.tidyverse.org/) | Makes working with strings in R easier         |
+-------------------------------------------+------------------------------------------------+
| [forcats](https://forcats.tidyverse.org/) | Operations for using categorical variables     |
+-------------------------------------------+------------------------------------------------+

::: {.box .note}
Notice the `dplyr::filter()` syntax in the `Conflicts` section. `filter` is
defined as a function in both the `dplyr` package as well as the base R `stats`
package. The `stats` package is loaded by default when you run R, and thus the
`filter` function is defined (specifically, it performs [linear filtering on
time series
data](https://www.rdocumentation.org/packages/stats/versions/3.6.2/topics/filter)).
However, when `dplyr` is loaded, it also has a `filter` function which overrides
the definition from the `stats` package. This is why the tidyverse package
reports this as a conflict when loaded:

```
-- Conflicts ------------------------------------------------ tidyverse_conflicts() --
x dplyr::filter() masks stats::filter()
```

This is tidyverse telling you that the `filter` function has been redefined and
you should make sure you are aware of that.

However, if you did want to use the original `stats` defined `filter` function,
you may still access it using the `::` namespace operator. This operator lets
you "look inside" a loaded package, for example `dplyr`, and access a function
within the namespace of that package:

```
library(dplyr)
# the filter() function definition is now from the dplyr package, and not from the stats package
# the following two lines of code execute the same function
filter(df)
dplyr::filter(df)
# to access the stats definition of the filter function, use the namespace operator
stats::filter(df)
```

Most functions defined by a package can be accessed using the `::` operator, and
it is often a good idea to do so, to ensure you are calling the right function.

:::

## The tibble

Data in tidyverse is organized primarily in a special data frame object called a
`tibble`. The `tibble()` function is defined in the [tibble
package](https://tibble.tidyverse.org/) of the tidyverse:

```
library(tibble) # or
library(tidyverse)
tbl <- tibble(
    x = rnorm(100, mean=20, sd=10),
    y = rnorm(100, mean=50, sd=5)
)
tbl
# A tibble: 100 x 2
       x     y
   <dbl> <dbl>
 1 16.5   54.6
 2 14.4   54.3
 3  7.87  53.7
 4  8.06  50.8
 5 37.2   57.1
 6 16.5   51.9
 7 15.8   50.1
 8 40.3   44.3
 9 12.0   49.8
10 23.8   50.1
# ... with 90 more rows
```

A `tibble` stores rectangular data, i.e. a grid of data elements with where
every column has the same number of rows.

## Importing Data

## pipes

## Tidying Data

## Arranging Data {#dw-arranging}
